# Taffybar log levels
# Format: LoggerName: LEVEL
# Levels: DEBUG INFO NOTICE WARNING ERROR CRITICAL ALERT EMERGENCY
#
# This file exists to selectively enable verbose logging when debugging.
# Normal/default operation should keep the log quiet (root logger is set to
# WARNING in `taffybar.hs`).
#
# Example (uncomment as-needed):
# System.Taffybar.DBus.Toggle: DEBUG
# Graphics.UI.GIGtkStrut: DEBUG
{}
