flags: {}
extra-package-dbs: []
packages:
- .
- location: ./taffybar
  extra-dep: true
- location: ../xmonad/xmonad-contrib
  extra-dep: true
- location: ../xmonad/xmonad
  extra-dep: true
- location:
    git: git@github.com:IvanMalison/github.git
    commit: af73bd9e193b045a25bccf86061858db21091508
  extra-dep: true
# - location: ../../../../Projects/status-notifier-item
#   extra-dep: true
# - location: ../../../../Projects/gtk-sni-tray
#   extra-dep: true
extra-deps:
- ConfigFile-1.1.4
- X11-1.8
- X11-xft-0.3.1
- containers-0.5.11.0
- dbus-1.0.1
- dbus-hslogger-0.1.0.1
- gi-cairo-connector-0.0.1
- gi-cairo-render-0.0.1
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.1
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.16
- gi-gdkx11-3.0.4
- gi-gio-2.0.16
- gi-glib-2.0.17
- gi-gtk-3.0.26
- gi-gtk-hs-0.3.6.3
- gi-pango-1.0.16
- gi-xlib-2.0.2
- gio-0.13.4.1
- gtk-sni-tray-0.1.6.0
- gtk-strut-0.1.3.0
- haskell-gi-0.21.2
- haskell-gi-base-0.21.2
- libxml-sax-0.7.5
- rate-limit-1.4.1
- spool-0.1
- status-notifier-item-0.3.0.0
- stm-2.5.0.0
- time-units-1.0.0
- xml-helpers-1.0.0
resolver: lts-13.2
allow-newer: true
nix:
  packages:
    - cairo
    - gcc
    - gnome2.pango
    - gobjectIntrospection
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu-glib
    - libdbusmenu-gtk3
    - libxml2
    - numix-icon-theme-circle
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
