scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_multiplier` to 0.
  faux_multiplier: 3

  # Automatically scroll to the bottom when new text is written
  # to the terminal.
  auto_scroll: false

font:
  size: 8

# Colors (Gotham)
colors:
  # Default colors
  primary:
    background: '0x0a0f14'
    foreground: '0x98d1ce'

  # Normal colors
  normal:
    black: '0x0a0f14'
    red: '0xc33027'
    green: '0x26a98b'
    yellow: '0xedb54b'
    blue: '0x195465'
    magenta: '0x4e5165'
    cyan: '0x33859d'
    white: '0x98d1ce'

  # Bright colors
  bright:
    black: '0x10151b'
    red: '0xd26939'
    green: '0x081f2d'
    yellow: '0x245361'
    blue: '0x093748'
    magenta: '0x888ba5'
    cyan: '0x599caa'
    white: '0xd3ebe9'

window:
  padding:
    x: 10
    y: 10
  decorations: full
